// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxqy1CuH2kx8Z07NnZrTqqYDEgYEbc8DY',
    appId: '1:37290099778:android:9dd471045caaaeb0ca19db',
    messagingSenderId: '37290099778',
    projectId: 'learnovate-31ad9',
    databaseURL: 'https://learnovate-31ad9-default-rtdb.firebaseio.com',
    storageBucket: 'learnovate-31ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ71FdRe1zIX2PPoERbZaTdgR6A4R7Fds',
    appId: '1:37290099778:ios:b22195591c37b253ca19db',
    messagingSenderId: '37290099778',
    projectId: 'learnovate-31ad9',
    databaseURL: 'https://learnovate-31ad9-default-rtdb.firebaseio.com',
    storageBucket: 'learnovate-31ad9.appspot.com',
    iosClientId: '37290099778-cvltciiafb9ukq9au7spv3v36sihvge8.apps.googleusercontent.com',
    iosBundleId: 'com.haryanaassociationofkenya',
  );
}
